version: "3.8"

services:
  nginx:
    image: nginx:latest
    env_file:
      - ./.env
    ports:
      - ${HOST_PORT}:80
    restart: unless-stopped
    container_name: ${APP_NAME}-nginx
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      NGINX_APP_ROOT:  ${NGINX_APP_ROOT}
      NGINX_INDEX_FILE: ${NGINX_INDEX_FILE}
      NGINX_PHP_SERVER: ${APP_NAME}-php
    volumes:
      - ./codebase/${REPO_NAME}:/var/www/html/${REPO_NAME}:delegated
      - ./templates:/var/templates:ro
      # - ./logs/nginx:/logs/nginx:delegated   #only uncomment if neeed to ouput logs  here ( need to edit the default.template to save the log files here)
      # - ./configs/nginx/hosts:/etc/nginx/conf.d:delegated   #Only use if you need additional configuration or debug the generated config
    command: /bin/bash -c "envsubst '$$NGINX_APP_ROOT $$NGINX_INDEX_FILE $$NGINX_PHP_SERVER $$S3_URI' < /var/templates/nginx/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - docker-ecommerce-network
  php-fpm:
    build: .
    restart: unless-stopped
    container_name: ${APP_NAME}-php
    environment:
      APP_ENV: ${APP_ENV}
      PHP_IDE_CONFIG: serverName=${APP_NAME}
    volumes:
        - ./codebase/${REPO_NAME}:/var/www/html/${REPO_NAME}:delegated
        - ./configs/php/custom-php-config.ini:/usr/local/etc/php/conf.d/custom-php-config.ini:ro
        - ./configs/php/www2.conf:/usr/local/etc/php-fpm.d/www2.conf:ro
        - ./configs/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        # - ./logs/xdebug:/logs/xdebug:delegated   #uncomment if you whant to save profiles or xdebug logs ( need to change xdebug.ini log file location )
        # - ./logs/php:/logs/php:delegated  #uncomment if you whant to save logs here ( need to change www2.conf log file location )
    networks:
        - docker-ecommerce-network
        
networks:
  docker-ecommerce-network:
    external: true

