FROM php:7.4-fpm

 RUN docker-php-ext-install mysqli \
   && docker-php-ext-install pdo_mysql \
   && pecl install redis-5.2.2 \
   && docker-php-ext-enable redis\
   && pecl install xdebug \
   && docker-php-ext-enable xdebug \
   && apt-get update\
   && apt-get install git -y