version: "3.8"

services:
  nginx:
    image: nginx:latest
    env_file:
      - ./.env
    ports:
      - ${HOST_PORT}:${HOST_PORT}
    restart: unless-stopped
    container_name: ${CONTAINER_NAME}
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${HOST_PORT}
      HTTPS_METHOD: noredirect
      NGINX_APP_ROOT:  ${NGINX_APP_ROOT}
      NGINX_INDEX_FILE: ${NGINX_INDEX_FILE}
      NGINX_PHP_SERVER: php-${CONTAINER_NAME}
      NGINX_SERVER_NAME: ${CONTAINER_NAME}
      S3_URI: ${S3_URI}
    volumes:
      - ./codebase/${REPO_NAME}:/var/www/html/${REPO_NAME}:delegated
      - ./templates:/var/templates:ro
      # - ./logs/nginx:/logs/nginx:delegated   #only uncomment if neeed to ouput logs  here ( need to edit the default.template to save the log files here)
      # - ./configs/nginx/hosts:/etc/nginx/conf.d:delegated   #Only use if you need additional configuration or debug the generated config
    command: /bin/bash -c "envsubst '$$NGINX_APP_ROOT $$NGINX_INDEX_FILE $$NGINX_PHP_SERVER  $$VIRTUAL_PORT $$NGINX_SERVER_NAME $$S3_URI' < /var/templates/nginx/default.template > /etc/nginx/conf.d/default.conf && cp -n /var/templates/wp/wp-config.php  ${NGINX_APP_ROOT}/wp-config.php && exec nginx -g 'daemon off;'"
    networks:
      - docker-ecommerce-network
  php-fpm:
    build: .
    restart: unless-stopped
    container_name: php-${CONTAINER_NAME}
    environment:
      WP_HTTPS: ${HTTPS}
      WP_ENV: ${WP_ENV}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PHP_IDE_CONFIG: serverName=${CONTAINER_NAME}
    volumes:
        - ./codebase/${REPO_NAME}:/var/www/html/${REPO_NAME}:delegated
        - ./configs/php/custom-php-config.ini:/usr/local/etc/php/conf.d/custom-php-config.ini:ro
        - ./configs/php/www2.conf:/usr/local/etc/php-fpm.d/www2.conf:ro
        - ./configs/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        # - ./logs/xdebug:/logs/xdebug:delegated   #uncomment if you whant to save profiles or xdebug logs ( need to change xdebug.ini log file location )
        # - ./logs/php:/logs/php:delegated  #uncomment if you whant to save logs here ( need to change www2.conf log file location )
    networks:
        - docker-ecommerce-network

networks:
  docker-ecommerce-network:
    external: true

