FROM php:7.4-fpm

 RUN docker-php-ext-install mysqli \
    && docker-php-ext-install pdo_mysql \
    && pecl install redis-5.2.2 \
    && docker-php-ext-enable redis\
    && pecl install xdebug-2.8.1 \
    && docker-php-ext-enable xdebug
